// Regenerates src/data/catalog.ts from the design prototype in design/.
//
// The prototype is the catalog's source of truth. Executing its own eras()
// method and emitting TypeScript from the result means the shipped data
// cannot drift from the design. Run after editing the prototype:
//
//   node scripts/generate-catalog.mjs
//
// Entry ids are the prototype's glyph codes, which are stable and unique, so
// regenerating never remaps saved progress.
import fs from 'node:fs';

const PROTOTYPE = 'design/Road to Doomsday.dc.html';
const OUTPUT = 'src/data/catalog.ts';
const SEED = 'supabase/seed/catalog.sql';

const src = fs.readFileSync(PROTOTYPE, 'utf8');
const match = src.match(/<script type="text\/x-dc" data-dc-script data-props="\{\}">([\s\S]*?)<\/script>/);
if (!match) throw new Error(`no dc script block found in ${PROTOTYPE}`);

const Component = new Function(
  match[1].replace('class Component extends DCLogic', 'class Component') + '\nreturn Component;',
)();
const eras = new Component().eras();

const q = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const isNumbered = (eps) =>
  eps.every((t, i) => t === 'EPISODE ' + String(i + 1).padStart(2, '0'));

const out = [];
out.push("import type { Era } from './types';");
out.push('');
out.push('/** Placeholder titles for series whose episode names we do not list. */');
out.push('const numbered = (n: number): string[] =>');
out.push("  Array.from({ length: n }, (_, i) => `EPISODE ${String(i + 1).padStart(2, '0')}`);");
out.push('');
out.push('/**');
out.push(' * The full rewatch catalog, in story order (in-universe chronology), grouped');
out.push(' * into eras. Ported from the Claude Design prototype in `design/`.');
out.push(' */');
out.push('export const CATALOG: readonly Era[] = [');

for (const er of eras) {
  out.push('  {');
  out.push(`    id: ${q(er.id)},`);
  out.push(`    name: ${q(er.name)},`);
  out.push(`    span: ${q(er.span)},`);
  out.push(`    dialect: ${q(er.dialect)},`);
  if (er.parallel) out.push('    parallel: true,');
  out.push('    palette: {');
  out.push(`      bg: ${q(er.bg)},`);
  out.push(`      ink: ${q(er.ink)},`);
  out.push(`      sub: ${q(er.sub)},`);
  out.push(`      accent: ${q(er.a)},`);
  out.push(`      card: ${q(er.cb)},`);
  out.push(`      border: ${q(er.bd)},`);
  out.push(`      posterBg: ${q(er.pbg)},`);
  out.push(`      posterInk: ${q(er.pink)},`);
  out.push(`      texture: ${q(er.tex)},`);
  out.push('    },');
  out.push('    entries: [');
  for (const e of er.entries) {
    out.push('      {');
    out.push(`        id: ${q(e.glyph)},`);
    out.push(`        kind: ${q(e.kind)},`);
    out.push(`        title: ${q(e.t)},`);
    out.push(`        year: ${q(e.y)},`);
    if (e.kind === 'film') {
      out.push(`        minutes: ${e.r},`);
    } else {
      if (isNumbered(e.eps)) {
        out.push(`        episodes: numbered(${e.eps.length}),`);
      } else {
        out.push('        episodes: [');
        for (const t of e.eps) out.push(`          ${q(t)},`);
        out.push('        ],');
      }
      out.push(`        episodeMinutes: ${e.epMin},`);
    }
    out.push(`        tier: ${e.tier},`);
    out.push(`        stingers: ${e.st},`);
    out.push(`        clue: ${q(e.clue)},`);
    if (e.svc) out.push(`        service: ${q(e.svc)},`);
    if (e.url) out.push(`        url: ${q(e.url)},`);
    if (e.drop) out.push(`        drop: ${q(e.drop)},`);
    out.push('      },');
  }
  out.push('    ],');
  out.push('  },');
}
out.push('];');
out.push('');
out.push('/** Every entry, flattened out of its era. */');
out.push('export const ALL_ENTRIES = CATALOG.flatMap((era) => era.entries);');
out.push('');

fs.writeFileSync(OUTPUT, out.join('\n'));
const count = eras.reduce((n, er) => n + er.entries.length, 0);
console.log(`${OUTPUT}: ${eras.length} eras, ${count} entries`);

// --------------------------------------------------------------- SQL seed --
// The Supabase catalog tables are seeded from this same pass, so the remote
// catalog and the bundled fallback can never describe different things.

const sq = (v) => (v == null ? 'null' : "'" + String(v).replace(/'/g, "''") + "'");
const sqlJson = (v) => "'" + JSON.stringify(v).replace(/'/g, "''") + "'::jsonb";

const seed = [];
seed.push('-- GENERATED by scripts/generate-catalog.mjs — do not edit.');
seed.push('--');
seed.push('-- Seeds the catalog tables. Run in the Supabase SQL editor AFTER');
seed.push('-- migrations/0001_init.sql. Re-running replaces the catalog in place.');
seed.push('--');
seed.push('-- Deletes are scoped to the catalog only; progress rows reference');
seed.push('-- entries, so removing an entry also drops anyone\'s progress against');
seed.push('-- it — which is exactly what removing it from the catalog means.');
seed.push('');
seed.push('begin;');
seed.push('');
seed.push('delete from public.entries;');
seed.push('delete from public.eras;');
seed.push('');
seed.push(
  'insert into public.eras (id, position, name, span, dialect, parallel, palette) values',
);
seed.push(
  eras
    .map((er, i) =>
      `  (${sq(er.id)}, ${i}, ${sq(er.name)}, ${sq(er.span)}, ${sq(er.dialect)}, ` +
      `${er.parallel ? 'true' : 'false'}, ${sqlJson({
        bg: er.bg,
        ink: er.ink,
        sub: er.sub,
        accent: er.a,
        card: er.cb,
        border: er.bd,
        posterBg: er.pbg,
        posterInk: er.pink,
        texture: er.tex,
      })})`,
    )
    .join(',\n') + ';',
);
seed.push('');
seed.push(
  'insert into public.entries (id, era_id, position, kind, title, year, minutes,\n' +
    '                            episodes, episode_minutes, tier, stingers, clue,\n' +
    '                            service, url, drop_label) values',
);

const rows = [];
for (const er of eras) {
  er.entries.forEach((e, i) => {
    const film = e.kind === 'film';
    rows.push(
      `  (${sq(e.glyph)}, ${sq(er.id)}, ${i}, ${sq(e.kind)}, ${sq(e.t)}, ${sq(e.y)}, ` +
        `${film ? e.r : 'null'}, ` +
        `${film ? 'null' : sqlJson(e.eps)}, ${film ? 'null' : e.epMin}, ` +
        `${e.tier}, ${e.st}, ${sq(e.clue)}, ${sq(e.svc)}, ${sq(e.url)}, ${sq(e.drop)})`,
    );
  });
}
seed.push(rows.join(',\n') + ';');
seed.push('');
seed.push('commit;');
seed.push('');

fs.mkdirSync('supabase/seed', { recursive: true });
fs.writeFileSync(SEED, seed.join('\n'));
console.log(`${SEED}: ${eras.length} eras, ${count} entries`);
